### ISSUE TITLE
WSDL returning no data

### ISSUE THREAD

**Issue by jegjessing** [spring-guides/gs-consuming-web-service#27]
Hi, any chance of having the project updated soon or suggestions for alternate wsdl's than stock quote.
At the moment all it return is exception, so the example does not work well at the moment

**Comment by dsyer** [comment]
Works for me. What's the issue exactly? Maybe you need to configure an HTTP proxy or something?

**Comment by Nxtra** [comment]
Hi, I also have the issue. Either when calling the service from the application or directly from the website. When entering a company symbol it returns exeption.
For example:
Given I am on webpage http://www.webservicex.com/stockquote.asmx?op=GetQuote
When I enter MSFT as value
When I press 'Invoke'
Then I get <string xmlns="http://www.webserviceX.NET/">exception</string> as response

Same thing happens when accessing from the mobile network with my phone.
Also, when using the application to call the service, I see 'exception' being printed. 

Is there an issue with the SOAP service?
